name: 'Tests Workflow'

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 8 * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

      - name: Run tests
        run: dotnet test --logger "html;logfilename=report.html"

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: Report
          path: TestResults/report.html
          retention-days: 3
